# Generated by Django 5.1.1 on 2024-09-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('ultima_sesion', models.DateTimeField(auto_now_add=True)),
                ('administrador', models.BooleanField(default=False)),
                ('personal', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=False)),
                ('superadministrador', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
