# Generated by Django 5.1.1 on 2024-09-06 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='personal',
            new_name='is_staff',
        ),
    ]
