# Generated by Django 5.1.1 on 2024-09-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0002_rename_personal_cuenta_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='ciudad',
            field=models.CharField(default='Desconocido', max_length=50),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='departamento',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
    ]
