# Generated by Django 4.2.14 on 2024-09-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, max_length=255)),
                ('imagen', models.ImageField(blank=True, upload_to='fotos/categorias')),
            ],
        ),
    ]
